version: '3.8'

networks:
  megaservice_network:
    driver: bridge
    
services:
  #megaservice:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: megaservice
  #  ports:
  #    - "8888:8888"
  #  ipc: host
  #  restart: always
  speecht5-service:
    build:
      context: .
      dockerfile: Dockerfile.speecht5
    container_name: speecht5-service
    ports:
      - ${SPEECHT5_PORT:-7055}:7055
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      XLA_FLAGS: "--xla_cpu_enable_fast_math=false"
      JAX_PLATFORM_NAME: "cpu"
      JAX_ENABLE_X64: "True"
    networks:
      - megaservice_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7055/health"]
      interval: 10s
      timeout: 6s
      retries: 18  
  tts-speecht5:
    build:
      context: .
      dockerfile: Dockerfile.tts
    container_name: tts-speecht5-service
    ports:
      - ${TTS_PORT:-9088}:9088
    ipc: host
    environment:
      TTS_ENDPOINT: http://speecht5-service:7055
      TTS_COMPONENT_NAME: ${TTS_COMPONENT_NAME:-OPEA_SPEECHT5_TTS}
      XLA_FLAGS: "--xla_cpu_enable_fast_math=false"
      JAX_PLATFORM_NAME: "cpu"
      JAX_ENABLE_X64: "True"
    networks:
      - megaservice_network
    depends_on:
      speecht5-service:
        condition: service_healthy
  
  
